jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: setting up python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: update pip
        run: python -m pip intall --upgrade pip 
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run tests
        run: pytest