name: Build and Deploy
on: [push, pull_request]

jobs:
  job1:
    environment: 
      name: testing
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: password
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: ajsdnasdjnwmsaldlw9320481djkahhjkqh2812dak
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 50

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: fastapi
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s 
          --health-timeout 5s 
      

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: setting up python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: update pip
        run: python -m pip install --upgrade pip 
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run tests 10
        run: pytest 
      